"""Make liked column nullable

Revision ID: f00796f523a3
Revises: 815f081725e5
Create Date: 2025-03-15 13:42:47.101809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00796f523a3'
down_revision = '815f081725e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie_data', schema=None) as batch_op:
        batch_op.alter_column('liked',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_movie_data', schema=None) as batch_op:
        batch_op.alter_column('liked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
